#ifndef NETWORKPROGRAM_CONSTANT_H
#define NETWORKPROGRAM_CONSTANT_H

#define SEPARATOR "#"
#define SEPARATOR_HISTORY "#|"

#define X_ICON 1
#define O_ICON 2

#define NEXT_YOU 1
#define NEXT_NOT_YOU 2
#define END_GAME 3

#define MAX_LEN_BUFF 1024

#define PREFIX_END_GAME "$END_GAME"
#define PREFIX_SUCCESS "$OK"
#define PREFIX_LOGIN "$LOGIN"
#define PREFIX_REGISTER "$REGISTER"
#define PREFIX_HISTORY "$HISTORY"
#define PREFIX_ONLINE "$ONLINE"
#define PREFIX_MESSAGE "$MESSAGE"
#define PREFIX_CELL "$CELL"
#define PREFIX_NEW_GAME "$NEW_GAME"
#define PREFIX_ACCEPT_PLAY "$ACCEPT_PLAY"
#define PREFIX_CLOSE "$CLOSE"
#define PREFIX_PLAY "$PLAY"
#define PREFIX_WIN "$WIN"
#define PREFIX_LOST "$LOST"
#endif

